services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=https://fakestoreapi.com
    restart: always
    ports:
      - '3000:3000'
  storybook:
      build:
        context: .
        dockerfile: ./.storybook/Dockerfile
      restart: always
      ports:
        - '6006:80'
