services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - ./.env.production
  storybook:
      build:
        context: .
        dockerfile: ./.storybook/Dockerfile
      restart: always
      ports:
        - '6006:80'
