import type { Metadata } from 'next'
import { Comic_Neue } from 'next/font/google'

import { AppLayout } from '~/components/providers/layout'
import type { AppChildren } from '~/types'

import '~/styles/globals.css'

export const metadata: Metadata = {
  title: 'Mikantama',
  description: 'Generated by create next app'
}

const base = Comic_Neue({
  subsets: ['latin'],
  weight: ['300', '400', '700']
})

const RootLayout = ({ children }: AppChildren) => {
  return (
    <html lang="en">
      <body className={base.className}>
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  )
}

export default RootLayout
